# Alembic script template
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '47af8b518046'
down_revision = '2c3d9f1e6baf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('availability_slots')
    op.drop_table('payments')
    op.drop_table('professional_reviews')
    op.drop_table('consultation_sessions')
    op.drop_table('professional_profiles')
    op.create_index(op.f('ix_daily_meal_logs_logged_at'), 'daily_meal_logs', ['logged_at'], unique=False)
    op.create_index(op.f('ix_daily_meal_logs_user_id'), 'daily_meal_logs', ['user_id'], unique=False)
    op.create_index('ix_daily_meal_logs_user_logged_at', 'daily_meal_logs', ['user_id', 'logged_at'], unique=False)
    op.create_index(op.f('ix_image_analysis_logs_analyzed_at'), 'image_analysis_logs', ['analyzed_at'], unique=False)
    op.create_index('ix_image_analysis_logs_user_analyzed_at', 'image_analysis_logs', ['user_id', 'analyzed_at'], unique=False)
    op.create_index('ix_image_analysis_logs_user_id', 'image_analysis_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_image_analysis_logs_user_id', table_name='image_analysis_logs')
    op.drop_index('ix_image_analysis_logs_user_analyzed_at', table_name='image_analysis_logs')
    op.drop_index(op.f('ix_image_analysis_logs_analyzed_at'), table_name='image_analysis_logs')
    op.drop_index('ix_daily_meal_logs_user_logged_at', table_name='daily_meal_logs')
    op.drop_index(op.f('ix_daily_meal_logs_user_id'), table_name='daily_meal_logs')
    op.drop_index(op.f('ix_daily_meal_logs_logged_at'), table_name='daily_meal_logs')
    op.create_table('professional_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('specialization', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('years_experience', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('certifications', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('languages', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('verification_document_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('approved_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('consultation_price_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('consultation_duration_mins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('average_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_reviews', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_sessions_completed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('is_accepting_clients', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('max_clients_per_week', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='professional_profiles_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='professional_profiles_pkey'),
    sa.UniqueConstraint('user_id', name='professional_profiles_user_id_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('consultation_sessions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('professional_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('specialization_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('session_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('duration_mins', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('session_price_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('professional_earnings_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('flexa_commission_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('commission_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('meeting_link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('payment_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], name='consultation_sessions_professional_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='consultation_sessions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='consultation_sessions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('professional_reviews',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('professional_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('helpful_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], name='professional_reviews_professional_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['consultation_sessions.id'], name='professional_reviews_session_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='professional_reviews_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='professional_reviews_pkey'),
    sa.UniqueConstraint('session_id', name='professional_reviews_session_id_key')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('professional_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('stripe_payment_intent_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('stripe_customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('gross_amount_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('flexa_commission_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('professional_payout_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('payout_status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('refund_amount_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('refund_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('refunded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], name='payments_professional_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['consultation_sessions.id'], name='payments_session_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='payments_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='payments_pkey')
    )
    op.create_table('availability_slots',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('professional_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('booked_session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booked_session_id'], ['consultation_sessions.id'], name='availability_slots_booked_session_id_fkey'),
    sa.ForeignKeyConstraint(['professional_id'], ['professional_profiles.id'], name='availability_slots_professional_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='availability_slots_pkey')
    )
    # ### end Alembic commands ###
