# Alembic script template
from alembic import op
import sqlalchemy as sa


revision = 'bd22ed08b2da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar_state',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('bmi_category', sa.String(length=30), nullable=False),
    sa.Column('avatar_class', sa.String(length=30), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('personality_mode', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_avatar_state_user_id'), 'avatar_state', ['user_id'], unique=True)
    op.create_table('chat_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_memory_created_at'), 'chat_memory', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_memory_user_id'), 'chat_memory', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_memory_user_id'), table_name='chat_memory')
    op.drop_index(op.f('ix_chat_memory_created_at'), table_name='chat_memory')
    op.drop_table('chat_memory')
    op.drop_index(op.f('ix_avatar_state_user_id'), table_name='avatar_state')
    op.drop_table('avatar_state')
    # ### end Alembic commands ###
